import { keywords as base, keywords2 as base2 } from '../base/keywords';

export const keywords: Record<string, string> = {
  ...base,
  abstract: 'abstract',
  any: 'any',
  as: 'as',
  asserts: 'asserts',
  async: 'async',
  await: 'await',
  bigint: 'bigint',
  boolean: 'boolean',
  break: 'break',
  case: 'case',
  catch: 'catch',
  class: 'class',
  const: 'const',
  constructor: 'constructor',
  continue: 'continue',
  debugger: 'debugger',
  declare: 'declare',
  default: 'default',
  delete: 'delete',
  do: 'do',
  else: 'else',
  enum: 'enum',
  export: 'export',
  extends: 'extends',
  false: 'false',
  finally: 'finally',
  for: 'for',
  from: 'from',
  function: 'function',
  get: 'get',
  if: 'if',
  implements: 'implements',
  import: 'import',
  in: 'in',
  infer: 'infer',
  instanceof: 'instanceof',
  interface: 'interface',
  is: 'is',
  keyof: 'keyof',
  let: 'let',
  module: 'module',
  namespace: 'namespace',
  never: 'never',
  new: 'new',
  null: 'null',
  number: 'number',
  object: 'object',
  package: 'package',
  private: 'private',
  protected: 'protected',
  public: 'public',
  readonly: 'readonly',
  require: 'require',
  globalThis: 'globalThis',
  return: 'return',
  set: 'set',
  static: 'static',
  string: 'string',
  super: 'super',
  switch: 'switch',
  symbol: 'symbol',
  this: 'this',
  throw: 'throw',
  true: 'true',
  try: 'try',
  type: 'type',
  typeof: 'typeof',
  undefined: 'undefined',
  unique: 'unique',
  unknown: 'unknown',
  var: 'var',
  void: 'void',
  while: 'while',
  with: 'with',
  yield: 'yield',
};

export const keywords2: Record<string, string> = {
  ...base2,
};
