import { Complex, Simple } from './code';
import { JsonType, UnreachableError, AssertError, Language } from './type';

export class Func {
  core2class(complex: typeof Complex, simple: typeof Simple<Complex>, key: string, json: Record<string, any>): Complex;
  core2class(
    complex: typeof Complex,
    simple: typeof Simple<Complex>,
    key: string,
    json: Record<string, any>,
    parent: Complex,
  ): Complex | Simple<Complex>;
  core2class(
    complex: typeof Complex,
    simple: typeof Simple<Complex>,
    key: string,
    json: Record<string, any>,
    parent?: Complex,
  ): Complex | Simple<Complex> | undefined {
    const array: boolean[] = [];
    while (Array.isArray(json)) {
      // 先取 1，再用 0 复写，注意反过来会有问题
      array.push(json[1] === null);
      json = json[0];
    }

    const optional = key.endsWith('?');
    key = optional ? key.slice(0, -1) : key;

    const type = this.type(json);
    switch (type) {
      case JsonType.String:
      case JsonType.Number:
      case JsonType.Boolean:
        if (!parent) {
          this.unreachableError('simple must have a parent type');
        }
        // @ts-ignore
        return new simple(key, array, optional, json, parent, type);

      case JsonType.Object:
        // @ts-ignore
        const self = new complex(key, array, optional, json, parent);
        self.child = Object.keys(json)
          .map(k => this.core2class(complex, simple, k, json[k], self))
          .filter(e => e);
        return self;

      case JsonType.Null:
      // config empty array, has not item
      // unit test
      case JsonType.Undefined:
        break;

      default:
        this.unreachableError(`core2class parsed an unknown typeof ${type}`);
    }

    return undefined;
  }

  convertWrap(str: string) {
    // 可能引发换行的字符
    const special: Record<string, string> = {
      '\n': '\\n',
      '\r': '\\r',
      '\f': '\\f',
      '\v': '\\v',
      '\b': '\\b',
      '\t': '\\t',
      '\\': '\\\\',
      $: '\\$',
      "'": "\\'",
    };
    return str.replace(new RegExp(`[${Object.keys(special).join('')}\\\\]`, 'g'), e => {
      const t = special[e];
      if (t) {
        return t;
      }
      return this.unreachableError('convertWrap');
    });
  }

  quickHash(str: string, max: number) {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = (hash * 31 + str.charCodeAt(i)) % Math.pow(10, max);
    }
    return hash.toString().padStart(max, '0');
  }

  convertKeyword(str: string, keywords: Record<string, string>, restore: boolean) {
    const max = 3;
    const splitKey = '_';
    const startKey = 'k';

    if (!restore) {
      if (keywords[str]) {
        return `${startKey}${this.quickHash(str, max)}${str}`;
      }
      let [, x] = str.match(new RegExp('^(\\d)')) ?? [];
      x = x ? `${splitKey}${x.charCodeAt(0)}${splitKey}` : '';
      x = `${x}${str.slice(x ? 1 : 0).replace(/[^a-zA-Z0-9_]/g, e => `${splitKey}${e.charCodeAt(0)}${splitKey}`)}`;
      if (x.startsWith('_')) {
        x = `${startKey}${this.quickHash(str, max)}${x}`;
      }
      return x;
    }

    // quickHash 算法是必须的，因为不仅仅是下划线开头，keywords 也需要加前导
    // quickHash 算法在 3 位数参数的情况下，针对 10 位字符串的 hash 冲突的概率只有 0.5%
    // 这 0.5% 只有在使用 restore 时，才会触发，如果是单向转换，永远不会有问题

    let x = str.replace(new RegExp(`${splitKey}(\\d+)${splitKey}`, 'g'), (_, e) => String.fromCharCode(e));
    const [, hash] = x.match(new RegExp(`^${startKey}(\\d{${max})`)) ?? [];
    if (hash) {
      const t = x.slice(max + 1);
      return hash === this.quickHash(t, max) ? t : x;
    }
    this.unreachableError('convertKeyword restore can not be used');
    return x;
  }

  addX(child: string) {
    return `${String.fromCharCode(60)}${child}${String.fromCharCode(62)}`;
  }

  toUpperCaseFirst(str: string) {
    if (str.length) {
      return `${str.substring(0, 1).toUpperCase()}${str.substring(1)}`;
    } else {
      return str;
    }
  }

  clearComment(str: string) {
    return str.replace(/\s*\/\/.*$/gm, '').replace(/^\s*\n/gm, '');
  }

  addCopyRight(tool: 'json2class' | 'json2http') {
    return `
/**
 * Licensed under the ISC License. See LICENSE file for details.
 * Copyright (c) ${new Date().getFullYear()} Yang Fan, China ${this.addX('yangfanzn@gmail.com')}
 * This file is auto-generated by [${tool}].
 * Do not modify this file manually, as changes will be overwritten.
 */
 
`;
  }

  type(o: any) {
    return Object.prototype.toString.call(o).slice(8, -1).toLowerCase();
  }

  unreachableError(message: string, detail?: string): any {
    const list = [
      'the occurrence of this error indicates an unexpected situation in the program,',
      'please report this error to the author[yangfanzn@163.com]. Thank you very much!\n',
    ];
    if (detail) {
      list.unshift(detail);
    }
    list.unshift(message);
    throw new UnreachableError(list.join('\n'));
  }

  assertError(message: string, detail?: string): any {
    const list: string[] = [];
    if (detail) {
      list.push(detail);
    }
    list.push(message);
    throw new AssertError(list.join('\n'));
  }

  language(language: Language) {
    const languages: Record<Language, { ext: string; desc: string }> = {
      [Language.Dart3]: { ext: 'dart', desc: 'dart' },
      // [Language.ArkTs5]: { ext: 'ets', desc: 'arkTs' },
    };
    return languages[language];
  }
}

export const func = new Func();
