import base from '../base/keywords';

export const keywords: Record<string, string> = {
  ...base,
  as: 'as',
  break: 'break',
  class: 'class',
  continue: 'continue',
  do: 'do',
  else: 'else',
  false: 'false',
  for: 'for',
  fun: 'fun',
  if: 'if',
  in: 'in',
  interface: 'interface',
  is: 'is',
  null: 'null',
  object: 'object',
  package: 'package',
  return: 'return',
  super: 'super',
  this: 'this',
  throw: 'throw',
  true: 'true',
  try: 'try',
  typealias: 'typealias',
  typeof: 'typeof',
  val: 'val',
  var: 'var',
  when: 'when',
  while: 'while',

  by: 'by',
  catch: 'catch',
  constructor: 'constructor',
  delegate: 'delegate',
  dynamic: 'dynamic',
  field: 'field',
  file: 'file',
  finally: 'finally',
  get: 'get',
  import: 'import',
  init: 'init',
  param: 'param',
  property: 'property',
  receiver: 'receiver',
  set: 'set',
  setparam: 'setparam',
  value: 'value',
  where: 'where',

  abstract: 'abstract',
  actual: 'actual',
  annotation: 'annotation',
  companion: 'companion',
  const: 'const',
  crossinline: 'crossinline',
  // data: 'data',
  enum: 'enum',
  expect: 'expect',
  external: 'external',
  final: 'final',
  infix: 'infix',
  inline: 'inline',
  inner: 'inner',
  internal: 'internal',
  lateinit: 'lateinit',
  noinline: 'noinline',
  open: 'open',
  operator: 'operator',
  out: 'out',
  override: 'override',
  private: 'private',
  protected: 'protected',
  public: 'public',
  reified: 'reified',
  sealed: 'sealed',
  suspend: 'suspend',
  tailrec: 'tailrec',
  vararg: 'vararg',

  it: 'it',
};
