name: json2http
description: "json2http"
version: 0.0.1

keywords:
  - http request
  - http
  - https
  - json2http
  - json2class
  - json
  - json5
  - class
  - cli
  - config
  - transform
  - code generator
  - code build
  - serialization
  - deserialization
  - typescript
  - dart
  - arkTs

homepage: https://github.com/yangfanzn/json2any/tree/main/packages/json2http
repository: https://github.com/yangfanzn/json2any

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
