name: json2class
description: "A CLI tool to generate class objects from JSON or JSON5, supporting serialization and deserialization."
version: 0.0.5

keywords:
  - json2class
  - json
  - json5
  - class
  - cli
  - config
  - transform
  - code generator
  - code build
  - serialization
  - deserialization
  - typescript
  - dart
  - arkTs


homepage: https://github.com/yangfanzn/json2any/tree/main/packages/json2class
repository: https://github.com/yangfanzn/json2any

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
