import { keywords as base, keywords2 as base2 } from '../base/keywords';

export const keywords: Record<string, string> = {
  ...base,
  _: '_',
  Any: 'Any',
  as: 'as',
  associatedtype: 'associatedtype',
  break: 'break',
  case: 'case',
  catch: 'catch',
  class: 'class',
  continue: 'continue',
  default: 'default',
  defer: 'defer',
  deinit: 'deinit',
  do: 'do',
  else: 'else',
  enum: 'enum',
  extension: 'extension',
  fallthrough: 'fallthrough',
  false: 'false',
  fileprivate: 'fileprivate',
  for: 'for',
  func: 'func',
  guard: 'guard',
  if: 'if',
  import: 'import',
  in: 'in',
  init: 'init',
  inout: 'inout',
  internal: 'internal',
  is: 'is',
  let: 'let',
  nil: 'nil',
  operator: 'operator',
  precedencegroup: 'precedencegroup',
  private: 'private',
  protocol: 'protocol',
  Protocol: 'Protocol',
  public: 'public',
  repeat: 'repeat',
  rethrows: 'rethrows',
  return: 'return',
  self: 'self',
  Self: 'Self',
  static: 'static',
  struct: 'struct',
  subscript: 'subscript',
  super: 'super',
  switch: 'switch',
  throw: 'throw',
  throws: 'throws',
  true: 'true',
  try: 'try',
  Type: 'Type',
  typealias: 'typealias',
  var: 'var',
  where: 'where',
  while: 'while',
  // special word used by baseDef in file: swift/code.ts
  NSNumber: 'NSNumber',
};

export const keywords2: Record<string, string> = {
  ...base2,
};
